name: Update Zigbee2MQTT
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new Zigbee2MQTT version (no dash on the end)'
        required: true
        type: string
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configuration
        run: |
          cd zigbee2mqtt2
          jq --arg v "${{ inputs.version }}-1" '.version = ($v)' config.json > config.tmp
          mv config.tmp config.json
      - name: Changelog
        run: |
          cd zigbee2mqtt2
          echo -e "## ${{ inputs.version }}-1\n- Updated Zigbee2MQTT to version [`${{ inputs.version }}`](https://github.com/Koenkk/zigbee2mqtt/releases/tag/${{ inputs.version }})\n\n" | cat - CHANGELOG.md > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update to Zigbee2MQTT ${{ inputs.version }}
          title: Zigbee2MQTT ${{ inputs.version }}
          branch: update-${{ inputs.version }}
